import type { YouTubeCaptionTrack } from "../shared/types";

export interface YouTubeCaptionControlsState {
  isYouTubeWatch: boolean;
  tracks: YouTubeCaptionTrack[];
  selectedTrackId?: string;
  status: string;
}

export interface YouTubeCaptionControlsCallbacks {
  onRefresh?(): void;
  onStart(trackId: string): void;
  onStop(): void;
}

export function isYouTubeWatchUrl(url: string | undefined): boolean {
  if (!url) return false;
  try {
    const parsed = new URL(url);
    return /(^|\.)youtube\.com$/i.test(parsed.hostname) && parsed.pathname === "/watch" && parsed.searchParams.has("v");
  } catch {
    return false;
  }
}

export function defaultYouTubeCaptionTrackId(tracks: YouTubeCaptionTrack[]): string {
  return tracks.find((track) => track.languageCode.toLowerCase().startsWith("en") || /english/i.test(track.name))?.id ?? tracks[0]?.id ?? "";
}

export function renderYouTubeCaptionControls(
  root: HTMLElement,
  state: YouTubeCaptionControlsState,
  callbacks: YouTubeCaptionControlsCallbacks
): void {
  root.replaceChildren();
  const title = document.createElement("h2");
  title.textContent = "유튜브 자막 번역";

  const status = document.createElement("p");
  status.className = "muted";
  status.dataset.role = "youtube-caption-status";
  status.textContent = state.isYouTubeWatch ? state.status || "자막 트랙을 선택한 뒤 번역을 시작하세요." : "YouTube 영상 페이지에서 사용할 수 있습니다.";

  const select = document.createElement("select");
  select.dataset.role = "youtube-caption-track";
  select.disabled = !state.isYouTubeWatch || state.tracks.length === 0;
  select.replaceChildren(...state.tracks.map((track) => new Option(captionTrackLabel(track), track.id)));
  select.value = state.selectedTrackId && state.tracks.some((track) => track.id === state.selectedTrackId)
    ? state.selectedTrackId
    : defaultYouTubeCaptionTrackId(state.tracks);

  const label = document.createElement("label");
  label.textContent = "자막 트랙";
  label.append(select);

  const refresh = button("트랙 새로고침", "refresh-youtube-caption", () => callbacks.onRefresh?.(), !state.isYouTubeWatch);
  const start = button(
    "번역 시작",
    "start-youtube-caption",
    () => callbacks.onStart(select.value),
    !state.isYouTubeWatch || !select.value
  );
  const stop = button("번역 끄기", "stop-youtube-caption", callbacks.onStop, !state.isYouTubeWatch);

  root.append(title, status, label, row([refresh, start, stop]));
}

function captionTrackLabel(track: YouTubeCaptionTrack): string {
  return `${track.name} (${track.languageCode}${track.isAutoGenerated ? ", 자동 생성" : ""})`;
}

function button(label: string, action: string, onClick: () => void, disabled = false): HTMLButtonElement {
  const node = document.createElement("button");
  node.type = "button";
  node.textContent = label;
  node.dataset.action = action;
  node.disabled = disabled;
  node.addEventListener("click", onClick);
  return node;
}

function row(children: HTMLElement[]): HTMLElement {
  const wrapper = document.createElement("div");
  wrapper.className = "button-row";
  wrapper.append(...children);
  return wrapper;
}
