export type ProfilePurpose = "page" | "selection" | "image" | "dictionary" | "dictionary-source" | "general" | "youtube-caption";

export type DictionaryTermSource = "source" | "translation";

export type SelectionResultDisplayMode = "drawer" | "bubble";

export type GeneralTranslatorDisplayMode = "drawer" | "tab";

export type YouTubeCaptionPosition = "above" | "below";

export type MessageRole = "system" | "user" | "assistant";

export type ReasoningEffort = "minimal" | "low" | "medium" | "high";

export type ProviderType =
  | "openai"
  | "claude"
  | "gemini"
  | "ollama-local"
  | "ollama-cloud"
  | "custom-openai-compatible";

export interface PromptMessage {
  role: MessageRole;
  content: string;
}

export interface GenerationParameters {
  maxTokens?: number;
  maxOutputTokens?: number;
  temperature?: number;
  topP?: number;
  reasoningEffort?: ReasoningEffort;
}

export interface PromptProfile {
  id: string;
  purpose: ProfilePurpose;
  name: string;
  providerId: string;
  model: string;
  parameters: GenerationParameters;
  messages: PromptMessage[];
}

export interface RenderedPrompt {
  model: string;
  parameters: GenerationParameters;
  messages: PromptMessage[];
  image?: ProviderImagePayload;
}

export interface ProviderImagePayload {
  dataUrl: string;
  mimeType: string;
  base64: string;
}

export interface ProviderConfig {
  id: string;
  type: ProviderType;
  name: string;
  apiKey?: string;
  baseUrl?: string;
}

export interface DictionaryEntry {
  id: string;
  term: string;
  sourceText: string;
  explanation: string;
  createdAt: string;
}

export interface TranslationHistoryEntry {
  id: string;
  sourceText: string;
  translatedText: string;
  createdAt: string;
  profileId: string;
  profileName: string;
  providerId: string;
  model: string;
}

export interface YouTubeCaptionTrack {
  id: string;
  name: string;
  languageCode: string;
  baseUrl: string;
  isAutoGenerated?: boolean;
}

export interface ExtensionState {
  providerConfigs: ProviderConfig[];
  promptProfiles: PromptProfile[];
  activeProfileByPurpose: Record<ProfilePurpose, string>;
  dictionaryEntries: DictionaryEntry[];
  translationHistory: TranslationHistoryEntry[];
  selectionModeEnabled: boolean;
  selectionResultDisplayMode: SelectionResultDisplayMode;
  generalTranslatorDisplayMode: GeneralTranslatorDisplayMode;
  youtubeCaptionPosition: YouTubeCaptionPosition;
}

export type BackgroundRequest =
  | { type: "translatePage"; texts: string[] }
  | { type: "translateSelection"; text: string }
  | { type: "translateImage"; imageUrl: string }
  | { type: "translateGeneral"; text: string; profileId?: string }
  | { type: "deleteTranslationHistoryEntry"; id: string }
  | { type: "clearTranslationHistory" }
  | { type: "openGeneralTranslator"; sourceText?: string; translatedText?: string }
  | { type: "getYouTubeCaptionTracks"; tabId: number }
  | { type: "startYouTubeCaptionTranslation"; tabId: number; trackId: string }
  | { type: "stopYouTubeCaptionTranslation"; tabId: number }
  | { type: "translateYouTubeCaptionBatch"; content: string }
  | { type: "generateDictionaryEntry"; term: string; sourceText: string; translationContext?: string; termSource?: DictionaryTermSource }
  | { type: "saveDictionaryEntry"; entry: DictionaryEntry }
  | { type: "deleteDictionaryEntry"; id: string }
  | { type: "restorePage" }
  | { type: "getState" }
  | { type: "saveState"; state: ExtensionState };

export type BackgroundResponse =
  | { ok: true; text?: string; texts?: string[]; state?: ExtensionState; tracks?: YouTubeCaptionTrack[]; selectedTrackId?: string }
  | { ok: false; error: string };
